# Site settings
title: Niram Factory
email: me@niram.org
description: > # this means to ignore newlines until "baseurl:"
  Design that celebrates life - made by yours truly -- Tharique Azeez
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://niram.xyz" # the base hostname & protocol for your site
twitter_username: enathu
github_username:  enathu

# Build settings
markdown: kramdown
